(in-package #:minecraft-3d)

(defun handle-input (player)
  "Handles keyboard input for player movement and rotation"
  (let ((speed 1.0))
    ;; Movement (WASD keys)
    (when (sdl:key-down-p :sdl-key-w)
      (incf (game-player-x player)
            (float (* speed (cos (game-player-rot-y player))) 0.0))
      (incf (game-player-z player)
            (float (* speed (sin (game-player-rot-y player))) 0.0)))
    (when (sdl:key-down-p :sdl-key-s)
      (decf (game-player-x player)
            (float (* speed (cos (game-player-rot-y player))) 0.0))
      (decf (game-player-z player)
            (float (* speed (sin (game-player-rot-y player))) 0.0)))
    (when (sdl:key-down-p :sdl-key-a)
      (decf (game-player-x player)
            (float (* speed (cos (+ (float (game-player-rot-y player) 0.0) (/ (float pi 0.0) 2.0)))) 0.0))
      (decf (game-player-z player)
            (float (* speed (sin (+ (float (game-player-rot-y player) 0.0) (/ (float pi 0.0) 2.0)))) 0.0)))
    (when (sdl:key-down-p :sdl-key-d)
      (incf (game-player-x player)
            (float (* speed (cos (+ (float (game-player-rot-y player) 0.0) (/ (float pi 0.0) 2.0)))) 0.0))
      (incf (game-player-z player)
            (float (* speed (sin (+ (float (game-player-rot-y player) 0.0) (/ (float pi 0.0) 2.0)))) 0.0)))

    ;; Vertical movement (Space and LShift)
    (when (sdl:key-down-p :sdl-key-space)
      (incf (game-player-y player) (float speed 0.0)))
    (when (sdl:key-down-p :sdl-key-lshift)
      (decf (game-player-y player) (float speed 0.0)))

    ;; Rotation (arrow keys)
    (when (sdl:key-down-p :sdl-key-left)
      (decf (game-player-rot-y player) (float 0.05 0.0)))
    (when (sdl:key-down-p :sdl-key-right)
      (incf (game-player-rot-y player) (float 0.05 0.0)))
    (when (sdl:key-down-p :sdl-key-up)
      (decf (game-player-rot-x player) (float 0.05 0.0)))
    (when (sdl:key-down-p :sdl-key-down)
      (incf (game-player-rot-x player) (float 0.05 0.0)))))
